# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from borValBadgeDbServer.models.base_model_ import Model
from borValBadgeDbServer.models.universe_info import UniverseInfo
from borValBadgeDbServer import util

from borValBadgeDbServer.models.universe_info import UniverseInfo  # noqa: E501

class Database(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, universes=None):  # noqa: E501
        """Database - a model defined in OpenAPI

        :param universes: The universes of this Database.  # noqa: E501
        :type universes: List[UniverseInfo]
        """
        self.openapi_types = {
            'universes': List[UniverseInfo]
        }

        self.attribute_map = {
            'universes': 'universes'
        }

        self._universes = universes

    @classmethod
    def from_dict(cls, dikt) -> 'Database':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Database of this Database.  # noqa: E501
        :rtype: Database
        """
        return util.deserialize_model(dikt, cls)

    @property
    def universes(self):
        """Gets the universes of this Database.


        :return: The universes of this Database.
        :rtype: List[UniverseInfo]
        """
        return self._universes

    @universes.setter
    def universes(self, universes):
        """Sets the universes of this Database.


        :param universes: The universes of this Database.
        :type universes: List[UniverseInfo]
        """

        self._universes = universes
