# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.universe_info import UniverseInfo
from openapi_server import util

from openapi_server.models.universe_info import UniverseInfo  # noqa: E501

class QueryByUniverseIdsGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """QueryByUniverseIdsGet200Response - a model defined in OpenAPI

        :param data: The data of this QueryByUniverseIdsGet200Response.  # noqa: E501
        :type data: List[UniverseInfo]
        """
        self.openapi_types = {
            'data': List[UniverseInfo]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'QueryByUniverseIdsGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _query_byUniverseIds_get_200_response of this QueryByUniverseIdsGet200Response.  # noqa: E501
        :rtype: QueryByUniverseIdsGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this QueryByUniverseIdsGet200Response.


        :return: The data of this QueryByUniverseIdsGet200Response.
        :rtype: List[UniverseInfo]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this QueryByUniverseIdsGet200Response.


        :param data: The data of this QueryByUniverseIdsGet200Response.
        :type data: List[UniverseInfo]
        """

        self._data = data
